spring:
  main:
    banner-mode: off
  application:
    name: Hibernate Demo
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      name: testdb
      url: jdbc:mysql://localhost:3306/hibernate_schema
      username: root
      password: rama123
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddlAuto: update